---

- include_tasks: kubernetes-server.yml

- include_tasks: kubectl-kubeconfig.yml
  when: "'masters' in group_names"

- include_tasks: kubernetes-master.yml
  when: "'masters' in group_names"

- include_tasks: kubernetes-node.yml
